version: 2
 
models:
  - name: dim_customers
    columns:
      - name: CUSTOMER_ID
        tests:
          - unique
          - not_null
 
  - name: fct_sales
    columns:
      - name: CUSTOMER_ID
        tests:
          - not_null
 
 